[workspace]
members = [
    "chromium-roots",
    "chromium-crs",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.85"
authors = ["0x676e67 <gngppz@gmail.com>"]
repository = "https://github.com/0x676e67/chromium-roots"
license = "BSD-3-Clause"

[workspace.dependencies]
anyhow = "1.0.100"
hex = "0.4.3"
p256 = "0.13.2"
prettyplease = "0.3"
proc-macro2 = "1"
prost = "0.14.1"
quote = "1"
rsa = "0.9.10"
rustls-pki-types = { version = "1.8", default-features = false }
serde_json = "1.0.145"
sha2 = { version = "0.10.9", features = ["oid"] }
syn = { version = "3", features = ["full"] }
ureq = { version = "3.1.4", default-features = false, features = ["rustls"] }
webpki = { package = "rustls-webpki", version = "0.103", features = ["alloc"] }
x509-parser = "0.18.0"
zip = { version = "=4.6.1", default-features = false, features = ["deflate"] }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
