[package]
name = "chromium-roots"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
description = "A maintainable Rust snapshot of the Chromium Root Store"
documentation = "https://docs.rs/chromium-roots"
repository = { workspace = true }
readme = "README.md"
license = { workspace = true }
keywords = ["chromium", "certificate", "root-store", "tls", "webpki"]
categories = ["cryptography", "web-programming"]
include = [
    "src/**",
    "tests/**",
    "examples/**",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "NOTICE",
    "CHROMIUM_LICENSE",
]

[dependencies]
rustls-pki-types = { workspace = true }

[dev-dependencies]
btls = "=0.5.6"
btls-sys = "=0.5.6"
foreign-types-shared = "0.3"
webpki = { workspace = true }
x509-parser = { workspace = true }


[lints]
workspace = true
